from django_backend.permissions.author import AuthorPermission
from django_backend.permissions.genre import GenrePermission
from django_backend.permissions.publishing_house import PublishingHousePermission
from django_backend.permissions.book_description import BookDescriptionPermission
from django_backend.permissions.book import BookPermission
