- name: deploy
  hosts: all
  tasks:
    - name: Ensure ansible user is in the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
      become: yes

    - name: create app dir
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/application"
        state: directory

    - name: copy .env
      ansible.builtin.template:
        src: example.env.j2
        dest: "{{ ansible_env.HOME }}/application/.env"

    - name: copy docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml.j2
        dest: "{{ ansible_env.HOME }}/application/docker-compose.yaml"

    - name: Check if docker-compose.yaml exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/application/docker-compose.yaml"
      register: compose_file_status

    - debug:
        var: compose_file_status.stat.exists
    
    - name: Log in to GitHub Container Registry
      ansible.builtin.shell: |
        echo "{{ lookup('env', 'GHCR_PAT') }}" | docker login ghcr.io -u {{ lookup('env', 'GITHUB_ACTOR') }} --password-stdin
      become: yes
    
    - name: Pull backend image
      ansible.builtin.shell: docker pull ghcr.io/bookstu/backend:latest
      become: yes

    - name: Pull frontend image
      ansible.builtin.shell: docker pull ghcr.io/bookstu/frontend:latest
      become: yes

    - name: Pull nginx image
      ansible.builtin.shell: docker pull ghcr.io/bookstu/nginx:latest
      become: yes

    - name: Pull database image
      ansible.builtin.shell: docker pull ghcr.io/bookstu/database:latest
      become: yes

    - name: start app
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_env.HOME }}/application"
        state: present
        recreate: always
