# Generated by Django 4.0.4 on 2024-12-07 14:55

from django.db import migrations, models
import django_backend.validators.file


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', validators=[django_backend.validators.file.validate_file])),
            ],
        ),
    ]
