# Generated by Django 4.0.4 on 2024-12-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_filemodel_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('patronymics', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_backend.filemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.TextField()),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(to='django_backend.author')),
                ('genres', models.ManyToManyField(to='django_backend.genre')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.publishinghouse')),
            ],
        ),
    ]
