# Generated by Django 4.2.17 on 2024-12-18 13:08

from django.db import migrations, models
import django_backend.validators.author


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0006_alter_author_id_alter_bookdescription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(validators=[django_backend.validators.author.validate_name]),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymics',
            field=models.TextField(blank=True, validators=[django_backend.validators.author.validate_patronymics]),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.TextField(validators=[django_backend.validators.author.validate_surname]),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='description',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.TextField(max_length=40),
        ),
    ]
