# Generated by Django 4.2.17 on 2024-12-21 21:41

from django.db import migrations, models
import django.db.models.deletion
import django_backend.validators.journal


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0010_alter_book_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('returned_date', models.DateTimeField(null=True, validators=[django_backend.validators.journal.validate_returned_date])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_backend.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend.profile')),
            ],
        ),
    ]
