# Generated by Django 4.2.17 on 2024-12-23 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_backend.validators.author
import django_backend.validators.book_description


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_backend', '0011_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(db_index=True, validators=[django_backend.validators.author.validate_name]),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymics',
            field=models.TextField(blank=True, db_index=True, validators=[django_backend.validators.author.validate_patronymics]),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.TextField(db_index=True, validators=[django_backend.validators.author.validate_surname]),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory_number',
            field=models.CharField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('0', 'Новая'), ('1', 'Хорошая'), ('2', 'Поношенная'), ('3', 'В ремонте'), ('4', 'Списана'), ('5', 'Утеряна')], db_index=True, default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookdescription',
            name='isbn',
            field=models.TextField(db_index=True, validators=[django_backend.validators.book_description.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='begin_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='returned_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_data',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymics',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
