name: Build and deploy
run-name: ${{ github.actor }} is running build and deploy
on:
  push:
    branches:
      - fix-ci-cd
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image: [backend, frontend, nginx]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}${{ matrix.image }}:latest
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}${{ matrix.image }}/cache
          context: ${{ matrix.image }}
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH 
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Run ansible script
        shell: bash 
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy-playbook.yml
