name: Build and deploy
run-name: ${{ github.actor }} is running build and deploy
on:
  push:
    branches:
      - fix-ci-cd
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set Repository Name to Lowercase
        id: set_repo_name
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push backend
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/backend
          cache: true
          cache-repository: ghcr.io/${{ env.REPO_NAME }}/backend/cache
          context: django_backend

      - name: Build and Push frontend
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/frontend
          cache: true
          cache-repository: ghcr.io/${{ env.REPO_NAME }}/frontend/cache
          context: react_frontend

      - name: Build and Push nginx
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/nginx
          cache: true
          cache-repository: ghcr.io/${{ env.REPO_NAME }}/nginx/cache
          context: nginx

  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          echo -e "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -H 82.97.246.215 >> ~/.ssh/known_hosts
      - name: Run Ansible Script
        shell: bash
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy-playbook.yaml
